{% set version = load_setup_py_data().get("version") %}  # In order for this to work we must install setuptools_scm prior to running conda-build, hopefully they'll fix that.

package:
  name: pwspy_gui
  version: {{ version }}

source:
  path: .. #tells conda-build that the source code is in the parent directory.

build:
  noarch: python
  number: 0
  entry_points:
    - PWSAnalysis = pwspy_gui.PWSAnalysisApp.__main__:main   # We must have an entry point specified for each entry point in setup.py or the noarch conda build will fail.
    - ERCreator = pwspy_gui.ExtraReflectanceCreator.__main__:main

requirements:
  build:
    - python >=3.7,<3.10  # In python 3.10 a change occurred so that PyQt no longer implicitly converts float to int. causees crashes.
    - setuptools
    - setuptools_scm

  run:
    - python >=3.7,<3.10
    - numpy >=1.16
    - psutil
    - shapely
    - pandas
    - matplotlib >=1.4
    - jsonschema
    - google-api-python-client 
    - google-auth-httplib2
    - google-auth-oauthlib
    - pyqt =5
    - pwspy >=1.0.1 # Core pws package, available on backmanlab anaconda cloud account.
    - mpl_qt_viz >1.0.9  # Plotting package available on PyPi and the backmanlab anaconda cloud account and conda-forge. Written for this project by Nick Anthony
    - descartes
    - cachetools >=4
app:
  entry: PWSAnalysis
  icon: cellLogo64.png  #The logo doesn't work :(
  summary: PWS Analysis GUI
  type: desk
  own_environment: False

about:
  home: https://github.com/nanthony21/pwspy_gui
  summary: 'A collection of GUIs providing users with easy access to PWS data analysis.'
  description: 'A collection of GUIs providing users with easy access to PWS data analysis.'
  doc_url: https://pwspy_gui.readthedocs.io/en/dev/
  dev_url: https://github.com/nanthony21/pwspy_gui
  
